name: Continuous Integration

on: [push, pull_request]
  # push:
  #   paths:
  #   - 'example/**'
  #   - 'skntk/**'
  #   - 'tests/**'
  # pull_request:
  #   paths: 
  #   - 'example/**'
  #   - 'skntk/**'
  #   - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setting up latest stable Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Analyzing files using flake8 with options
      run: |
        flake8 . --max-line-length=100 --show-source --statistics --ignore=F401,W503

  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        poetry-version: ["1.2.2"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Running Poetry image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Building and installing scikit-ntk
        run: |
          poetry build
          poetry install

      - name: Testing scikit-ntk
        run: |
          pytest