name: Python Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python-version: '3.x'

    steps:
    - uses: actions/checkout@v3

    - name: Setting up Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}
    
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Analyzing files using flake8 with options
      run: |
        flake8 . --max-line-length=100 --ignore=F401,W503